#ANDROID_TOOLCHAIN=/home/yhong/GS700C_5110_IPC_20160825/android/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8/bin
#/home/yhong/GS700C_5110_IPC_20160825/android/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8/bin
#gcc=arm-linux-androideabi-gcc


